<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { solveLameCylinder, type LameCylinderAxialCondition, type LameCylinderResult } from '../../../core/plate-shell'
import { evaluateNumericExpression } from '../../../core/numeric'
import { convertPresetValue, getPresetUnit, getUnitDefinition, normalizeToSI, type QuantityId, type UnitPresetId } from '../../../core/units'
import LameCylinderDiagram from './LameCylinderDiagram.vue'
import LameCylinderResults from './LameCylinderResults.vue'

type Field = 'innerRadius'|'outerRadius'|'evaluationRadius'|'elasticModulus'|'poissonRatio'|'internalPressure'|'externalPressure'|'axialForce'
interface Draft extends Record<Field,string>{boundary:LameCylinderAxialCondition|null}
const DEFAULT:Draft={boundary:null,innerRadius:'100',outerRadius:'200',evaluationRadius:'150',elasticModulus:'200000',poissonRatio:'0.3',internalPressure:'100',externalPressure:'0',axialForce:'0'}
const UNIT_FIELDS:ReadonlyArray<readonly[Field,QuantityId]>=[['innerRadius','length'],['outerRadius','length'],['evaluationRadius','length'],['elasticModulus','elasticModulus'],['internalPressure','pressure'],['externalPressure','pressure'],['axialForce','force']]
const draft=reactive<Draft>({...DEFAULT});const unitPreset=ref<UnitPresetId>('engineering');const materialPreset=ref<'manual'|'spcc'|'al-6061'>('manual');const result=ref<LameCylinderResult|null>(null);const errors=ref<string[]>([])
const units=computed(()=>({length:symbol('length'),elasticModulus:symbol('elasticModulus'),pressure:symbol('pressure'),force:symbol('force')}))
function symbol(quantity:QuantityId){const unit=getPresetUnit(quantity,unitPreset.value);return getUnitDefinition(quantity,unit).symbol}
function invalidate(){result.value=null;errors.value=[]}
function display(value:number){return String(Number(value.toPrecision(12)))}
function switchUnits(next:UnitPresetId){if(next===unitPreset.value)return;const current=unitPreset.value;for(const[field,quantity]of UNIT_FIELDS){if(draft[field].trim()==='')continue;try{const value=evaluateNumericExpression(draft[field]);const converted=convertPresetValue(value,quantity,current,next);if(converted!==null)draft[field]=display(converted)}catch{/* keep invalid draft */}}unitPreset.value=next}
function chooseBoundary(){if(draft.boundary==='plane-strain')draft.axialForce='0';invalidate()}
function applyMaterial(){if(materialPreset.value==='manual')return;const material=materialPreset.value==='spcc'?{e:205e9,nu:.3}:{e:69e9,nu:.33};const unit=getPresetUnit('elasticModulus',unitPreset.value);draft.elasticModulus=display(getUnitDefinition('elasticModulus',unit).fromSI(material.e));draft.poissonRatio=String(material.nu);invalidate()}
function parse(field:Field,label:string){try{return evaluateNumericExpression(draft[field])}catch(error){throw new Error(`${label}：${error instanceof Error?error.message:'输入无效'}`)}}
function si(field:Field,label:string,quantity:QuantityId){return normalizeToSI(parse(field,label),quantity,getPresetUnit(quantity,unitPreset.value))}
function calculate(){result.value=null;errors.value=[];try{if(!draft.boundary)throw new Error('必须显式选择轴向状态');result.value=solveLameCylinder({calculatorId:'lame-cylinder',boundary:draft.boundary,geometry:{kind:'lame-cylinder',innerRadiusM:si('innerRadius','内半径','length'),outerRadiusM:si('outerRadius','外半径','length')},material:{elasticModulusPa:si('elasticModulus','弹性模量','elasticModulus'),poissonRatio:parse('poissonRatio','泊松比')},load:{internalPressurePa:si('internalPressure','内压','pressure'),externalPressurePa:si('externalPressure','外压','pressure'),axialForceN:si('axialForce','轴力','force')},evaluationRadiusM:si('evaluationRadius','求值半径','length')})}catch(error){errors.value=[error instanceof Error?error.message:'Lamé 计算失败']}}
function reset(){Object.assign(draft,DEFAULT);unitPreset.value='engineering';materialPreset.value='manual';result.value=null;errors.value=[]}
</script>

<template><section class="calculator" aria-labelledby="lame-title">
  <header class="heading"><div><p>P3 · Gate P3-1B</p><h2 id="lame-title">厚壁圆筒 Lamé 解</h2><span>单层圆筒；压力为非负幅值；位移向外为正；内部统一 SI。</span></div><div class="unit-presets" role="group" aria-label="Lamé 单位制"><button type="button" :aria-pressed="unitPreset==='engineering'" :class="{active:unitPreset==='engineering'}" @click="switchUnits('engineering')">t–mm–s–N–MPa</button><button type="button" :aria-pressed="unitPreset==='si'" :class="{active:unitPreset==='si'}" @click="switchUnits('si')">SI（kg–m–s–N–Pa）</button></div></header>
  <div class="workspace-grid"><form class="input-panel" @submit.prevent="calculate">
    <fieldset class="full boundary"><legend>1. 轴向状态（必选）</legend><label><input v-model="draft.boundary" type="radio" value="open" @change="chooseBoundary">开口端</label><label><input v-model="draft.boundary" type="radio" value="closed" @change="chooseBoundary">封闭承压端</label><label><input v-model="draft.boundary" type="radio" value="plane-strain" @change="chooseBoundary">平面应变 εz=0</label></fieldset>
    <h3 class="full">2. 几何与求值位置</h3>
    <label><span>内半径 rᵢ</span><div class="unit-input"><input v-model="draft.innerRadius" aria-label="Lamé 内半径" inputmode="decimal" @input="invalidate"><b>{{units.length}}</b></div></label>
    <label><span>外半径 rₒ</span><div class="unit-input"><input v-model="draft.outerRadius" aria-label="Lamé 外半径" inputmode="decimal" @input="invalidate"><b>{{units.length}}</b></div></label>
    <label class="full"><span>求值半径 r（含边界）</span><div class="unit-input"><input v-model="draft.evaluationRadius" aria-label="Lamé 求值半径" inputmode="decimal" @input="invalidate"><b>{{units.length}}</b></div></label>
    <h3 class="full">3. 材料</h3><label class="full"><span>材料预设</span><select v-model="materialPreset" aria-label="Lamé 材料预设" @change="applyMaterial"><option value="manual">手工 / 验收基准</option><option value="spcc">SPCC 名义值</option><option value="al-6061">AL 6061-T6 名义值</option></select></label>
    <label><span>弹性模量 E</span><div class="unit-input"><input v-model="draft.elasticModulus" aria-label="Lamé 弹性模量" inputmode="decimal" @input="materialPreset='manual';invalidate()"><b>{{units.elasticModulus}}</b></div></label><label><span>泊松比 ν</span><div class="unit-input"><input v-model="draft.poissonRatio" aria-label="Lamé 泊松比" inputmode="decimal" @input="materialPreset='manual';invalidate()"><b>—</b></div></label>
    <h3 class="full">4. 压力与轴力</h3><label><span>内压 pᵢ（幅值）</span><div class="unit-input"><input v-model="draft.internalPressure" aria-label="Lamé 内压" inputmode="decimal" @input="invalidate"><b>{{units.pressure}}</b></div></label><label><span>外压 pₒ（幅值）</span><div class="unit-input"><input v-model="draft.externalPressure" aria-label="Lamé 外压" inputmode="decimal" @input="invalidate"><b>{{units.pressure}}</b></div></label>
    <label class="full"><span>居中轴力 F（拉为正）</span><div class="unit-input" :class="{disabled:draft.boundary==='plane-strain'}"><input v-model="draft.axialForce" aria-label="Lamé 外加轴力" inputmode="decimal" :disabled="draft.boundary==='plane-strain'" @input="invalidate"><b>{{units.force}}</b></div></label><p v-if="draft.boundary==='plane-strain'" class="full note">平面应变已约束 εz=0，不再叠加任意轴力。</p>
    <div class="full actions"><button type="submit">计算 Lamé 响应</button><button type="button" class="secondary" @click="reset">重置为新算例</button></div>
  </form><LameCylinderDiagram :boundary="draft.boundary" /></div>
  <div v-if="errors.length" class="error" role="alert"><strong>无法计算</strong><ul><li v-for="message in errors" :key="message">{{message}}</li></ul></div>
  <LameCylinderResults v-if="result" :result="result" :unit-preset="unitPreset" />
</section></template>

<style scoped>
.calculator{display:grid;gap:20px}.heading{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:20px 22px;border:1px solid var(--color-line);border-left:4px solid var(--color-brand);border-radius:12px;background:#f7faf9}.heading p{margin:0 0 5px;color:var(--color-brand);font-size:10px;font-weight:800}.heading h2{margin:0 0 5px;font-size:24px}.heading span{color:var(--color-muted);font-size:11px}.unit-presets{display:flex;flex:0 0 auto;gap:5px}.unit-presets button{min-height:38px;padding:0 10px;border:1px solid var(--color-line);border-radius:8px;color:#53636e;background:#fff;cursor:pointer;font-size:11px;font-weight:700}.unit-presets button.active{color:#fff;border-color:var(--color-brand);background:var(--color-brand)}
.workspace-grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(320px,.75fr);gap:18px;align-items:start}.input-panel{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px;min-width:0;padding:20px;border:1px solid var(--color-line);border-radius:var(--radius-large);background:var(--color-panel);box-shadow:var(--shadow-panel)}.input-panel h3{margin:4px 0 -1px;color:#30454e;font-size:13px}.input-panel label{display:grid;gap:6px;min-width:0;color:#53636e;font-size:12px;font-weight:700}.input-panel select{width:100%;min-height:42px;padding:0 10px;border:1px solid #cad5da;border-radius:8px;background:#fff}.full{grid-column:1/-1}.boundary{display:flex;flex-wrap:wrap;gap:13px 20px;margin:0;padding:13px;border:1px solid #cad5da;border-radius:9px}.boundary legend{padding:0 5px;color:#30454e;font-size:12px;font-weight:800}.boundary label{display:flex;align-items:center;gap:7px}.unit-input{display:grid;grid-template-columns:minmax(0,1fr) auto;min-height:42px;overflow:hidden;border:1px solid #cad5da;border-radius:8px;background:#fff}.unit-input:focus-within{border-color:var(--color-brand);box-shadow:0 0 0 3px rgb(18 106 115/10%)}.unit-input.disabled{opacity:.58}.unit-input input{min-width:0;padding:0 10px;border:0;outline:0}.unit-input b{display:grid;place-items:center;min-width:36px;padding:0 9px;border-left:1px solid #e2e7e9;color:#667881;background:#f7f9fa;font-size:10px}.note{margin:-5px 0 0;color:#76551e;font-size:10px}.actions{display:flex;gap:9px;margin-top:5px}.actions button{min-height:44px;padding:0 15px;border:0;border-radius:8px;color:#fff;background:var(--color-brand);cursor:pointer;font-weight:800}.actions .secondary{color:#53636e;border:1px solid var(--color-line);background:#f5f8f9}.error{padding:15px 18px;border-radius:9px;color:#8f342d;background:#fff0ed}.error ul{margin:6px 0 0}
@media(max-width:1000px){.heading{align-items:flex-start;flex-direction:column}.workspace-grid{grid-template-columns:1fr}}@media(max-width:600px){.heading,.input-panel{padding:16px}.unit-presets{width:100%;flex-direction:column}.input-panel{grid-template-columns:1fr}.full{grid-column:auto}.boundary{flex-direction:column}.actions{flex-direction:column}}
</style>
